### ISSUE TITLE
No module named OpenAI

### ISSUE THREAD

**Issue by CiquattroFPV** [muellerberndt/micro-gpt#24] opened 2023-04-19 07:21 UTC
I have this problem when I try to run with python 3.8 
I have tried with other version too but it get too  many errors

```
python3.8 microgpt.py "Programmatically draw a beautiful car and save the drawing in an image format of your choice on the Desktop." 
Traceback (most recent call last):
  File "microgpt.py", line 4, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
```

**Comment by Koalamanx** [comment] 2023-04-19 07:34
Same..

**Comment by muellerberndt** [comment] 2023-04-19 07:55
Did you install the requirements?

```
pip install -r requirements.txt
```

**Comment by CiquattroFPV** [comment] 2023-04-19 08:36
> Did you install the requirements?
> 
> ```
> pip install -r requirements.txt
> ```

of course.. I installed the openai module from pip too

**Comment by muellerberndt** [comment] 2023-04-19 08:45
Seems to be a common issue. Check out the answers to this [Stackoverflow question](https://stackoverflow.com/questions/71873182/no-module-named-openai).

**Comment by Koalamanx** [comment] 2023-04-19 09:21
whilst installing the requirments, it freezes and just does nothing here:

Collecting async-timeout<5.0,>=4.0.0a3
  Downloading https://www.piwheels.org/simple/async-timeout/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting mpmath>=0.19
  Downloading https://www.piwheels.org/simple/mpmath/mpmath-1.3.0-py3-none-any.whl (536 kB)
     |████████████████████████████████| 536 kB 126 kB/s
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/lib/python3/dist-packages (from torchvision->sentence-transformers>=2.2.2->chromadb==0.3.11->-r requirements.txt (line 9)) (8.1.2)
Building wheels for collected packages: duckdb, hnswlib
  **Building wheel for duckdb (setup.py) ... -**
  
  I just wait and wait and nothing happens. I managed to install openai regularly though, but when I run the script I get:
  
  Traceback (most recent call last):
  File "/home/kevin/micro-gpt/microgpt.py", line 5, in <module>
    from termcolor import colored
ModuleNotFoundError: No module named 'termcolor'

**Comment by muellerberndt** [comment] 2023-04-19 09:48
> I just wait and wait and nothing happens. I managed to install openai regularly though, but when I run the script I get:
> 
> Traceback (most recent call last): File "/home/kevin/micro-gpt/microgpt.py", line 5, in from termcolor import colored ModuleNotFoundError: No module named 'termcolor'

Run `pip install termcolor`.

**Comment by Koalamanx** [comment] 2023-04-19 11:29
Thanks also had to install duckduck go and dotenv. 

now it wants to install pinecone. How do i use something else

Set the MEMORY_TYPE environment variable to one of the supported backends:

chromadb
pinecone: Requires a [Pinecone](https://www.pinecone.io/) account and API key.
postgres: Requires the psycopg2 Python package and a postgres server with pg_vector installed.

How do I do this?

**Comment by muellerberndt** [comment] 2023-04-20 10:28
I believe we can close this since the error in the OP is caused by the [OpenAI library](https://github.com/openai/openai-python).

**Closed by muellerberndt** 2023-04-20 10:28 UTC
